name: 'snowpark_learn'
version: '1.0.0'
config-version: 2
profile: 'dbt_profile'



model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"

# define model variables
vars:
  stores: "1, 2, 3, 4"
  depts: "1, 2"
  test_date: "2012-01-01"

models:
  +persist_docs:
    relation: true
    columns: true
  use_anonymous_sproc: True
  snowpark_learn:
    materialized: view
    stg:
      materialized: view
      tables:
        - name: stg_sales_sample
    int:
      materialized: table
      tables:
        - name: int_sales_sample
