name: 'snowpark_learn'
version: '1.0.0'
config-version: 2
profile: 'dbt_profile'



model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"

on-run-start: "{{ create_stored_procedure() }}"

models:
  snowpark_learn:
    materialized: view
    stg:
      materialized: view
      tables:
        - name: stg_sales_sample
    int:
      materialized: table
      tables:
        - name: int_sales_sample
